//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SeisWide.rc
//
#define IDCANCEL2                       3
#define IDC_BUTTON_UPDATE               3
#define IDC_HELP_POLY                   3
#define IDR_SEISWITYPE_SRVR_IP          4
#define IDC_BUTTON_RELOAD               4
#define IDR_SEISWITYPE_SRVR_EMB         5
#define IDC_BUTTON_RELOAD_BW            5
#define IDR_SEISWITYPE_CNTR_IP          6
#define IDC_BUTTON_LOW                  6
#define IDC_BUTTON_LOW2                 7
#define IDC_BUTTON_FULL                 7
#define IDC_BUTTON_LOWER                8
#define IDC_BUTTON_LOWER2               9
#define IDC_BUTTON_HIGHER               9
#define IDC_BUTTON_RELOAD2              10
#define IDC_BUTTON_MORE_COLOR           10
#define IDC_BUTTON_MORE_COLOR2          11
#define IDC_BUTTON_BK_RED               11
#define IDC_BUTTON_SMALLBK              12
#define IDC_BUTTON_SMALLBK2             13
#define IDC_BUTTON_MORE_COLOR3          14
#define IDC_BUTTON_RELOAD_RedYELLOW     15
#define IDC_BUTTON_RELOAD_RedYELLOW2    16
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_INDICATOR_COORD              101
#define IDP_FAILED_TO_CREATE            102
#define IDB_LIGHTBULB                   104
#define IDD_TIP                         105
#define CG_IDS_TIPOFTHEDAY              106
#define CG_IDS_TIPOFTHEDAYMENU          107
#define CG_IDS_DIDYOUKNOW               108
#define CG_IDS_FILE_ABSENT              109
#define CG_IDP_FILE_CORRUPT             110
#define CG_IDS_TIPOFTHEDAYHELP          111
#define IDR_SEISWIDE                    112
#define IDR_DLGDECIMATE_TMPL            113
#define IDR_HTML_DLGSONOBUOYPOLY        114
#define IDR_HTML_DLGREGIONALVELOCITY    115
#define IDR_HTML_DLGREGIONALMODEL       116
#define IDR_HTML_DLGHARDWAREID          117
#define IDR_HTML_DLGHARDWAREID1         119
#define IDR_HTML_DLGHARDID              120
#define IDR_HTML_DLGHARDWAREID2         122
#define IDR_HTML_DLGVELOCITYPERTURB     124
#define IDR_HTML_CHTMLREGIDEMO          125
#define IDR_HTML_CDLGASCIIHEAD          126
#define ID_INDICATOR_THRESHOLD          127
#define IDR_MAINFRAME                   128
#define IDR_SEISWITYPE                  129
#define IDD_DIALOG_DIGITIZE             130
#define IDS_SEISALL                     130
#define IDS_SEISALLTYPE                 130
#define IDD_DLGREORGANIZE               131
#define IDD_DLGCOHMIX                   132
#define IDD_DLGNEWMODEL                 133
#define IDD_DLGRAYTRACING               134
#define IDD_DLG_MODEL_RESIZE            134
#define IDD_PRINT                       135
#define IDD_CHANGE_RANGES               136
#define IDD_DLG_LOADZELT                137
#define IDD_DEPTH                       138
#define IDD_TIMESEC                     140
#define IDD_VELOCITY                    141
#define IDD_DLG_FILTER1                 142
#define IDD_DLG_LATSHIFT                143
#define IDD_ADD_RANGES                  144
#define IDB_BITMAP2                     147
#define IDD_DLGRAYTRACING1              148
#define IDD_DLG_SEGYPREVIEW             149
#define IDD_BOUND_NODES                 151
#define IDD_DLGNEWLAYER                 152
#define IDD_LAYER_NODES                 153
#define IDD_DLGNEWVELFILE               154
#define IDD_DLG_SEGYINFO                155
#define IDB_BITMAP1                     156
#define IDB_BITMAP3                     158
#define IDD_DLG_TIM2DPTH                159
#define IDD_DLG_SOURCEPOS               160
#define IDD_DLG_FILLAREA                161
#define IDD_DLG_DIGRESOLUTION           162
#define IDD_DLG_SEGYCOLOR               163
#define IDD_DLG_SEGYAPPEND              164
#define IDD_DLG_VRED                    168
#define IDD_DLG_NOLABLES                169
#define IDD_DLG_MERGEMODELS             170
#define IDD_DLG_VZCURVE                 175
#define IDD_DLG_MIGPS                   176
#define IDD_DLG_TTCURVE                 177
#define IDD_DLD_INOUT                   178
#define IDD_DLG_KDMIG                   179
#define IDD_DLG_KDMIGPOST               180
#define IDD_DLG_TIMEBYTRC               181
#define IDD_DLG_HYDRATE                 184
#define IDD_DLG_SONOBOUY                187
#define IDD_DLGRAYTRACING_AUTO          194
#define IDD_DLG_TABLIZE_LAYER           196
#define IDD_DLG_LOADREID                197
#define IDD_DLG_LATLONG                 198
#define IDD_DLG_CONVERTDATSEGY          199
#define IDD_DLG_LINEDRAWTIM             200
#define IDD_DLG_LINEDRAWDEP             201
#define IDD_DLG_VEL2DEN                 202
#define IDD_DLG_VEL2DEN1                203
#define IDD_DLG_MIGLINEDRAW             204
#define IDD_DLG_DIGITIZE_SHIFT          205
#define IDD_DLG_EXPORT_BITMAP           206
#define IDD_DLG_INITAMP                 207
#define IDD_DLG_IMPORT_BITMAP           208
#define IDD_DLG_DIGLABEL                209
#define IDD_DLG_DIGOPTION               209
#define IDD_DLG_TIM2DPTH_BMP            210
#define IDD_DLG_DISP_BITMAP             211
#define IDD_DLG_UNIX2PC                 212
#define IDD_DLG_RESAMPLE                213
#define IDB_BITMAP_ZOOM                 215
#define IDI_ICON1                       216
#define IDD_DLG_WIENER_FILTER           219
#define IDD_DLG_WIENER_FILTER1          219
#define IDD_DIALOG1                     220
#define IDD_DLG_SHOWWIENER              220
#define IDD_DLG_DIGRESIZE               221
#define IDD_DLG_DIG_SETCURRENT          222
#define IDD_DLG_CHANGEREDUCE_BMP        223
#define IDD_DLG_MODEL_SHIFTBOUNDARY     224
#define IDD_DLG_LABEL_SIZES             225
#define IDD_DLG_INPUTVALUE              226
#define IDD_DLG_WIDE2DPTH               227
#define IDD_DLG_WIDE2VELOCITY           229
#define IDD_DLG_XLABEL                  230
#define IDD_DLG_SEGYCOLOR2              231
#define IDD_DLG_DIGITIZE_SHIFT1         232
#define IDD_DLG_SINE_MODULATE           232
#define IDD_DLG_DESPIKING               233
#define IDD_DIALOG_DECIMATE             234
#define IDD_DLG_ATTENUATERES            236
#define IDD_DLG_SEGYADD                 237
#define IDD_DLG_SEGY_ADD                237
#define IDD_DLG_RMSVELOCITY             238
#define IDD_DLG_AGC                     239
#define IDD_DLG_VELOCITY_TWTT2          240
#define IDD_DLG_SONOBOUY_POLY           241
#define IDD_DLG_SONOBOUY_AUTOOFFSET     242
#define IDD_DLG_SONOBOUY_DUB            243
#define IDD_DLG_FILTER_OFFSET           244
#define IDD_DLG_GAIN_ADJUST             245
#define IDD_DLG_SEGY_ADD2               245
#define IDD_DLG_POLYPOINTS              246
#define IDD_DIALOG_TRCBALANCEXT         247
#define IDD_DLG_DISTANCE_ADJUST         248
#define IDD_DLG_MODEL_THEORETICAL       249
#define IDD_DLG_HARDWAREID              250
#define IDD_DLG_VEL_PERTURB             252
#define IDD_DLG_REGI_DEMO               253
#define IDD_DLG_ASCIIHEAD               254
#define IDD_DLG_SHOTTABLE               255
#define IDD_DLG_TAUP                    256
#define IDD_DLG_TAUP1                   257
#define IDD_DLG_TAUP_INV                257
#define IDD_DLG_TFDN                    258
#define IDD_DLG_MAGMOD                  259
#define IDD_DLG_TIMEBYTRC_BMP           260
#define IDD_DLD_OFFSET_1TRC             261
#define IDD_DLG_BITMAP2SGY              262
#define IDD_DIALOG2                     263
#define IDD_DLG_FLOAT_VALUE             263
#define IDD_DLG_SEGYNORM_TRCINT         265
#define IDD_DLG_SOURCEPOS1              266
#define IDD_DLG_SOURCEPOS_BULK          266
#define IDD_DLG_POISSON                 267
#define IDD_ADD_RANGES1                 268
#define IDD_ADD_RANGES_FILE             268
#define IDD_DLG_FLOAT_VALUES_TWO        293
#define IDD_DLG_DEPTH2TIME              300
#define IDC_CONVERSION_ZMIN             1000
#define IDC_VIEW_UPDATE_XTICK           1000
#define IDC_EDIT_XMIN                   1000
#define IDC_BULB                        1000
#define IDC_CONVERSION_ZMAX             1001
#define IDC_VIEW_UPDATE_TTICK           1001
#define IDC_EDIT_XMAX                   1001
#define IDC_STARTUP                     1001
#define IDC_CONVERSION_VMIN             1002
#define IDC_CONVERSION_ZTICK            1002
#define IDC_NEXTTIP                     1002
#define IDC_CONVERSION_ZMAX2            1002
#define IDC_CONVERSION_VMAX             1003
#define IDC_VIEW_UPDATE_TMIN            1003
#define IDC_MIG_DXS                     1003
#define IDC_CONVERSION_VMINR            1004
#define IDC_VIEW_UPDATE_TMAX            1004
#define IDC_MIG_DT                      1004
#define IDC_TIPSTRING                   1004
#define IDC_VIEW_UPDATE_TMIN2           1004
#define IDC_CONVERSION_VMING            1005
#define IDC_VIEW_UPDATE_GAIN            1005
#define IDC_VIEW_UPDATE_TTICK2          1005
#define IDC_MIG_APERX                   1005
#define IDC_VIEW_UPDATE_SDEPTH          1005
#define IDC_VIEW_UPDATE_TMAX2           1005
#define IDC_CONVERSION_VMAXR            1006
#define IDC_VIEW_UPDATE_CLIP            1006
#define IDC_MIG_DA                      1006
#define IDC_VIEW_UPDATE_GDEPTH          1006
#define IDC_DIST                        1006
#define IDC_DIST_SHIFT                  1006
#define IDC_CONVERSION_VMAXG            1007
#define IDC_VIEW_UPDATE_VRED            1007
#define IDC_VIEW_UPDATE_TTICK3          1007
#define IDC_MIG_FA                      1007
#define IDC_VIEW_WIGGLE                 1008
#define IDC_REFNAME                     1008
#define IDC_CONVERSION_VMIDR            1008
#define IDC_MIG_AMIN                    1008
#define IDC_VIEW_UPDATE_VRED2           1008
#define IDC_VIEW_UPDATE_SRCPOS          1008
#define IDC_VIEW_AREA                   1009
#define IDC_CONVERSION_VMIDG            1009
#define IDC_EDIT_DIGITIZE               1009
#define IDC_MIG_FAC                     1009
#define IDC_VIEW_VRED                   1009
#define IDC_VIEW_UPDATE_TSTART          1009
#define IDC_VIEW_UPDATE_CLIP2           1009
#define IDC_VIEW_BOTH                   1010
#define IDC_CONVERSION_VMID             1010
#define IDC_EDIT_DIST                   1010
#define IDC_MIG_FZO                     1010
#define IDC_VIEW_SRCDEPTH               1010
#define IDC_VIEW_UPDATE_VRED3           1010
#define IDC_VIEW_XHYPERBOLA             1010
#define IDC_VELWATER                    1010
#define IDC_VIEW_FACEDOWN               1011
#define IDC_CONVERSION_VMIDR2           1011
#define IDC_MIG_DZO                     1011
#define IDC_VIEW_BUOYDEPTH              1011
#define IDC_CONVERSION_DV               1012
#define IDC_VIEW_UPDATE_XMIN            1012
#define IDC_CONVERSION_NV               1012
#define IDC_CONVERSION_DV1              1012
#define IDC_MIG_FS                      1012
#define IDC_VIEW_GUNDELAY               1012
#define IDC_CONVERSION_VMINB            1013
#define IDC_VIEW_UPDATE_XMAX            1013
#define IDC_MIG_DOFF                    1013
#define IDC_PROC_A                      1013
#define IDC_CONVERSION_VMAXB            1014
#define IDC_VIEW_UPDATE_SHOT1           1014
#define IDC_MIG_OFF0                    1014
#define IDC_VIEW_UPDATE_ZPROP           1014
#define IDC_VIEW_UPDATE_COL             1014
#define IDC_PROC_B                      1014
#define IDC_VIEW_UPDATE_SHOT2           1015
#define IDC_CONVERSION_VMIDB            1015
#define IDC_MIG_FMAX                    1015
#define IDC_VIEW_UPDATE_ROW             1015
#define IDC_PROC_C                      1015
#define IDC_VIEW_UPDATE_SHOTSTEP        1016
#define IDC_CONVERSION_VMIDG2           1016
#define IDC_VIEW_CDP                    1016
#define IDC_VIEW_UPDATE_XMAX2           1016
#define IDC_VIEW_UPDATE_DX              1016
#define IDC_VIEW_FACEUP                 1017
#define IDC_CONVERSION_VMIDB2           1017
#define IDC_CONVERSION_DZ2              1018
#define IDC_VIEW_OFFSET                 1018
#define IDC_CONVERSION_VMIDR3           1018
#define IDC_VIEW_UPDATE_DRIVENEW        1018
#define IDC_VIEW_GUNDEP                 1018
#define IDC_VIEW_OBSDEP                 1018
#define IDC_VIEW_DISTANCE               1019
#define IDC_VIEW_OFFSET2                1019
#define IDC_CONVERSION_VMIDG3           1019
#define IDC_MIGRATION_NX                1019
#define IDC_VIEW_UPDATE_ILLUMINATION    1019
#define IDC_VIEW_OBSDEP2                1019
#define IDC_VIEW_VELWATER               1019
#define IDC_VIEW_LOGSCALE_CEILING       1019
#define IDC_VIEW_LOGSCALE_THRESHOLD     1019
#define IDC_VIEW_ORIYES                 1020
#define IDC_VIEW_DISTANCE2              1020
#define IDC_CONVERSION_VMIDB3           1020
#define IDC_VIEW_WATERDEP               1020
#define IDC_VIEW_OFFSET3                1020
#define IDC_VIEW_AMPPOWER               1020
#define IDC_VIEW_ORINO                  1021
#define IDC_VIEW_ORIYES2                1021
#define IDC_CONVERSION_VMIDR4           1021
#define IDC_MIGRATION_NXPAD             1021
#define IDC_MIG_NA                      1021
#define IDC_MAXLEVELS                   1021
#define IDC_VIEW_LOGSCALE_THRESHOLD2    1021
#define IDC_TRAVELTIME                  1022
#define IDC_VIEW_ORINO2                 1022
#define IDC_CONVERSION_VMIDG4           1022
#define IDC_MIGRATION_LTAPER            1022
#define IDC_MIG_AMAX                    1022
#define IDC_VIEW_DIST                   1022
#define IDC_SEGY_ORDER                  1023
#define IDC_TRAVELTIME2                 1023
#define IDC_CONVERSION_VMIDB4           1023
#define IDC_MIG_ZMAX                    1023
#define IDC_VIEW_WATERDEP2              1023
#define IDC_GUNDEPTH                    1023
#define IDC_VIEW_DIST2                  1023
#define IDC_TIMESEC_TITLE               1024
#define IDC_CONVERSION_VMID2            1024
#define IDC_TRAVELTIME4                 1024
#define IDC_REFCDPTRUE                  1025
#define IDC_VIEW_UPDATE_FILLOFF         1025
#define IDC_CONVERSION_VMID3            1025
#define IDC_MIG_OFFMAX                  1025
#define IDC_REFFFIDTRUE                 1026
#define IDC_CONVERSION_VMID4            1026
#define IDC_MIG_ANGMAX                  1026
#define IDC_TRAVELTIME3                 1026
#define IDC_SEGY_AREAFILL_NEG           1026
#define IDC_PROCNAME_OUT                1027
#define IDC_CONVERSION_NV2              1027
#define IDC_CONVERSION_DV2              1027
#define IDC_MIG_V0                      1027
#define IDC_SEGY_WIGGLECHECK            1027
#define IDC_AVGAMP                      1027
#define IDC_CONVERSION_VMIDR5           1027
#define IDC_VIEW_AMPPOWER2              1027
#define IDC_PROCNAME_IN                 1028
#define IDC_CONVERSION_NV3              1028
#define IDC_CONVERSION_DV3              1028
#define IDC_MIG_DVZ                     1028
#define IDC_SEGY_AREAFILL_NEG2          1028
#define IDC_CONVERSION_VMIDG5           1028
#define IDC_PROC_SHOT1                  1029
#define IDC_CONVERSION_NV4              1029
#define IDC_CONVERSION_DV4              1029
#define IDC_MIG_MEMMAX                  1029
#define IDC_CONVERSION_VMIDB5           1029
#define IDC_SEGY_AREAFILL_NEG3          1029
#define IDC_IS_SWAPX                    1029
#define IDC_PROC_SHOT2                  1030
#define IDC_CONVERSION_NV5              1030
#define IDC_CONVERSION_DV5              1030
#define IDC_MIG_SRCDEPTH                1030
#define IDC_CONVERSION_VMID5            1030
#define IDC_IS_SWAPXLABEL               1030
#define IDC_IS_SWAPYLABEL               1030
#define IDC_CONVERSION_VMIDR6           1031
#define IDC_VIEW_TARGETDEP              1031
#define IDC_PROC_XMIN                   1032
#define IDC_CONVERSION_VMIDG6           1032
#define IDC_PROC_XMAX                   1033
#define IDC_CONVERSION_VMIDB6           1033
#define IDC_PROC_TMIN                   1034
#define IDC_CONVERSION_VMID6            1034
#define IDC_PROC_TMAX                   1035
#define IDC_CONVERSION_VMIDR7           1035
#define IDC_PROC_VELMIN                 1036
#define IDC_PROC_SAMPRATENEW            1036
#define IDC_CONVERSION_VMIDG7           1036
#define IDC_PROC_VELMAX                 1037
#define IDC_PROC_SAMPRATEOLD            1037
#define IDC_CONVERSION_VMIDB7           1037
#define IDC_PROC_TWINDOW                1038
#define IDC_PROC_SAMPLENNEW             1038
#define IDC_CONVERSION_VMID7            1038
#define IDC_PROC_DXMIX                  1039
#define IDC_PROC_NVSKIP                 1039
#define IDC_PROC_SAMPLENNEW2            1039
#define IDC_PROC_SAMPLENOLD             1039
#define IDC_CONVERSION_VMIDR8           1039
#define IDC_PROC_SHOTSTEP               1040
#define IDC_CONVERSION_VMIDG8           1040
#define IDC_PROC_DXMIX2                 1040
#define IDC_CONVERSIONDXV               1041
#define IDC_PROC_VRED                   1041
#define IDC_DLG_NLAYER                  1041
#define IDC_PROC_NSMOOTH                1041
#define IDC_REFCDP                      1042
#define IDC_DLG_XMIN                    1042
#define IDC_PROC_NUMCOH                 1042
#define ID_DIGITIZE_MIGNLAYER           1042
#define IDC_PROC_MAXLAG                 1042
#define IDC_CONVERSION_VMIDB8           1042
#define IDC_REFRANGE                    1043
#define IDC_DLG_XMAX                    1043
#define ID_DIGITIZE_MIGDV               1043
#define IDC_PROC_AMPMAX                 1043
#define IDC_PROC_MINLAG                 1043
#define IDC_CONVERSION_VMID8            1043
#define IDC_REFRANGE0                   1043
#define IDC_REFDX                       1044
#define IDC_DLG_ZMAX                    1044
#define ID_DIGITIZE_MIGSDIST            1044
#define IDC_PROC_MAXCORR                1044
#define IDC_CONVERSION_VMID9            1044
#define IDC_DLG_RAYTRACING              1045
#define IDC_DLG_ZMIN                    1045
#define ID_DIGITIZE_MIGSDEPTH           1045
#define IDC_PROC_MINCORR                1045
#define IDC_REFRANGE2                   1045
#define IDC_REF_TRACE                   1045
#define IDC_TRACE1                      1045
#define IDC_CONVERSION_VMIDR9           1045
#define IDC_DLG_VELNAME                 1046
#define ID_DIGITIZE_MIGXERR             1046
#define IDC_PROC_PNOISE                 1046
#define IDC_DLG_DIGNAME                 1046
#define IDC_CONVERSION_VMIDG9           1046
#define IDC_PRINTX                      1047
#define ID_DIGITIZE_MIGTERR             1047
#define IDC_PROC_DT                     1047
#define IDC_CONVERSION_VMIDB9           1047
#define IDC_PRINTY                      1048
#define ID_DIGITIZE_MIGAAMIN            1048
#define IDC_PROC_MINLAG2                1048
#define IDC_MOUSE_DOWN_X                1049
#define IDC_TIME_GAINDIST               1049
#define ID_DIGITIZE_MIGAAMAX            1049
#define IDC_PROC_MINLAGRATE             1049
#define IDC_MEMORYMAX                   1049
#define IDC_MOUSE_DOWNY                 1050
#define IDC_TIME_BASEGAIN               1050
#define ID_DIGITIZE_MIGMAXTRC           1050
#define IDC_MOUSE_UPX                   1051
#define IDC_TIME_BASEPOWER              1051
#define IDC_REFSHOT                     1051
#define IDC_MOUSE_UPY                   1052
#define IDC_REFSHOT2                    1052
#define IDC_TIME_GAINDIST2              1052
#define IDC_IS_TIME                     1052
#define IDC_IS_SHOWLABEL                1052
#define IDC_AVGMODE                     1052
#define IDC_BOUND_NUM                   1053
#define IDC_VEL_COLBAR                  1053
#define IDC_IS_SHOWLABEL2               1053
#define IDC_REV_POLARITY                1053
#define IDC_DLGV1MIN                    1054
#define IDC_VEL_CXPOS                   1054
#define IDC_DLGV1MAX                    1055
#define IDC_VEL_CYPOS                   1055
#define IDC_DLGNEWLAYER                 1056
#define IDC_VEL_VERT                    1056
#define IDC_VEL_VBARMIN                 1056
#define IDC_LAYERX                      1057
#define IDC_DLGV2MIN                    1057
#define IDC_VEL_CXEXT                   1057
#define IDC_DLG_ZELTNAME                1057
#define IDC_LAYERY                      1058
#define IDC_DLGV2MAX                    1058
#define IDC_VEL_CYEXT                   1058
#define IDC_PROC_FILTER                 1058
#define IDC_LAYERV                      1059
#define IDC_PROC_FILTERF1               1059
#define IDC_XMULT                       1059
#define IDC_LAYERNUM                    1060
#define IDC_PROC_FILTERF2               1060
#define IDC_REFKM                       1060
#define IDC_VEL_CYEXT2                  1060
#define IDC_XSHIFT                      1060
#define IDC_TIMESECNAME                 1061
#define IDC_PROC_FILTERF3               1061
#define IDC_PROC_FILTER2                1061
#define IDC_LAYER_ANISOTROPY            1061
#define IDC_PROC_FILTERF1X2             1061
#define IDC_VEL_CYPOS2                  1061
#define IDC_VEL_VBARMAX                 1061
#define IDC_PROC_NUMDIV                 1061
#define IDC_DEPTHSECNAME                1062
#define IDC_PROC_FILTERF4               1062
#define IDC_PROC_FILTERF10              1062
#define IDC_TIMESECNAME2                1062
#define IDC_VELNAME                     1062
#define IDC_LAYER_ANISOTROPY2           1062
#define IDC_LAYER0                      1062
#define IDC_OUTFILE                     1062
#define IDC_PROC_FILTERF2X2             1062
#define IDC_PROC_NUMLOOP                1062
#define IDC_VELSECNAME                  1063
#define IDC_PROC_FILTERF11              1063
#define IDC_PROC_FILTERF1X3             1063
#define IDC_VEL_NEWFILE                 1064
#define IDC_VELSECNAME2                 1064
#define IDC_PROC_FILTERF5               1064
#define IDC_PROC_NUM_TFILTER            1064
#define IDC_YMULT                       1064
#define IDC_COMBO_HEADINFO              1065
#define IDC_PROC_FILTERTA               1065
#define IDC_KM                          1065
#define IDC_SEPARATION_KM               1065
#define IDC_YSHIFT                      1065
#define IDC_VEL_TITLE                   1065
#define IDC_PROC_FILTERF12              1066
#define IDC_PROC_FILTERTAX2             1066
#define IDC_VTOLERANCE_PERC             1066
#define IDC_VEL_CRUISE                  1066
#define IDC_PROC_FILTERF13              1067
#define IDC_PROC_FILTERF2X3             1067
#define IDC_SEPARATION_KM2              1067
#define IDC_SHIFT_KM                    1067
#define IDC_VEL_AUTHOR                  1067
#define IDC_PROC_FILTERF1B              1068
#define IDC_VEL_COMPANY                 1068
#define IDC_PROC_FILTERF2B              1069
#define IDC_VEL_DATE                    1069
#define IDC_PROC_FILTERTB               1070
#define IDC_VEL_STARTLAT                1070
#define IDC_PROC_FILTERX1               1071
#define IDC_PROC_FILTER3                1071
#define IDC_PROC_ZEROPHASE              1071
#define IDC_VEL_STARTLONG               1071
#define IDC_PROC_SPHERICGAIN            1072
#define IDC_PROC_FILTERF1BX2            1072
#define IDC_PROC_HORZ                   1072
#define IDC_VEL_ENDLAT                  1072
#define IDC_PROC_SPHERORDER             1073
#define IDC_PROC_FILTERF2BX2            1073
#define IDC_PROC_HORZ2                  1073
#define IDC_PROC_AMP_PHASE              1073
#define IDC_VEL_ENDLONG                 1073
#define IDC_REFSEC                      1074
#define IDC_PROC_NORM                   1074
#define IDC_PROC_XPERCENT               1074
#define IDC_PROC_FILTERTBX2             1074
#define IDC_VEL_DEPLOYLAT               1074
#define IDC_PROC_NORMVALUE              1075
#define IDC_PROC_OFFSETMAX              1075
#define IDC_PROC_FILTERX2               1075
#define IDC_VEL_DEPLOYLONG              1075
#define IDC_PROC_MULTIPLY               1076
#define IDC_PROC_STACKWIDTH             1076
#define IDC_PROC_FILTERTAX3             1076
#define IDC_PROC_XPERCENT2              1076
#define IDC_VEL_SECNAME                 1076
#define IDC_PROC_MULTIPLYVALUE          1077
#define IDC_PROC_STACKWIDTH2            1077
#define IDC_PROC_FILTERF1BX3            1077
#define IDC_VEL_WELL_LAT                1077
#define IDC_DIG_FILEFORMAT              1078
#define IDC_PROC_ATTENUATIONCORR        1078
#define IDC_PROC_FILTERF2BX3            1078
#define IDC_PROC_IEEE_FLOAT             1078
#define IDC_VEL_WELL_LONG               1078
#define IDC_RADIO2                      1079
#define IDC_PROC_ATTENUATIONSEAFLOOR    1079
#define IDC_PROC_FILTERTBX3             1079
#define IDC_PROC_FILTER4                1079
#define IDC_RADIO16                     1080
#define IDC_PROC_MULTIPLY2              1080
#define IDC_PROC_HILBERT                1080
#define IDC_PROC_FILTERX3               1080
#define IDC_PROC_FILTER_TWICE           1081
#define IDC_RADIO18                     1081
#define IDC_RADIO19                     1082
#define IDC_VEL_WELL_DIST               1082
#define IDC_VEL_MAX_HORIZON_VALID       1083
#define IDC_VEL_DEPLOY_DIST             1084
#define IDC_VEL_FORMAT                  1085
#define IDC_BUTTON_BROWSET              1086
#define IDC_VIEW_FFID                   1086
#define IDC_VEL_DEPLOY_DEPTH            1086
#define IDC_BUTTON_BROWSED              1087
#define IDC_BUTTON_BROWSEVASCII         1087
#define IDC_BUTTON_BROWSETCOH           1087
#define IDC_BUTTON_REFRESH              1087
#define IDC_BUTTON_BROWSET2             1087
#define IDC_VEL_STARTDIST               1087
#define IDC_BUTTON_BROWSEV              1088
#define IDC_BUTTON_BROWSETXT            1088
#define IDC_SEGYINFO_SAMPINT            1089
#define IDC_BUTTON_BROWSEV2             1089
#define IDC_VEL_ENDDIST                 1089
#define IDC_SEGYINFO_NUMSAMP            1090
#define IDC_BUTTON_BROWSERIN            1090
#define IDC_BUTTON_BROWSEV3             1090
#define IDC_VEL_TITLE2                  1090
#define IDC_BUTTON_BROWSE_TX            1091
#define IDC_BUTTON_BROWSERIN2           1091
#define IDC_BUTTON_BROWSEV4             1091
#define IDC_BUTTON_BROWSEVRMS           1091
#define IDC_RADIO1                      1092
#define IDC_XSHOT                       1092
#define IDC_BUTTON_BROWSERIN3           1092
#define IDC_BUTTON_BROWSEDIG            1092
#define IDC_BUTTON_COLPATTERN           1092
#define IDC_TOTNTRACE                   1093
#define IDC_RAD_ONEOBJECT               1093
#define IDC_DLG_XYFILENAME              1093
#define IDC_RADIO14                     1093
#define IDC_BUTTON_COLPATTERN2          1093
#define IDC_XSHOT2                      1093
#define IDC_BUTTON_BROWSETPRE           1094
#define IDC_RADIO4                      1094
#define IDC_BUTTON_COLPATTERN3          1094
#define IDC_AVERAGEAMP                  1095
#define IDC_RADIO8                      1095
#define IDC_DLG_PROCESSING_SX           1095
#define IDC_RADIO20                     1095
#define IDC_XSHOT3                      1095
#define IDC_DIG_RESOLUTION              1096
#define IDC_RADIO15                     1096
#define IDC_DLG_PROCESSING_SX2          1096
#define IDC_DLG_FACTOR                  1096
#define IDC_RADIO21                     1096
#define IDC_BUTTON_COLPATTERN4          1096
#define IDC_DIG_NPOINT                  1097
#define IDC_DLG_PROCESSING_SY           1097
#define IDC_DIG_IVRAY                   1097
#define IDC_BUTTON_SAVE                 1097
#define IDC_DIG_NCURVE                  1098
#define IDC_BUTTON_LOAD                 1098
#define IDC_DIG_COMMENTS                1099
#define IDC_DLG_PROCESSING_SY2          1099
#define IDC_COL_MAXAMP_R                1100
#define IDC_COL_MAXAMP_G                1101
#define IDC_COL_MAXAMP_B                1102
#define IDC_COL_NEGAMP_R                1106
#define IDC_COL_NEGAMP_G                1107
#define IDC_COL_NEGAMP_B                1108
#define IDC_RADIO3                      1110
#define IDC_2NDSECNAME                  1111
#define IDC_RADIO17                     1111
#define IDC_2NDSECNAME2                 1112
#define IDC_OUTPUTSECNAME               1112
#define IDC_CHK_RENUMCDP                1113
#define IDC_EDIT_VRED                   1116
#define IDC_CHECK_NOLABELS              1118
#define IDC_CHECK_NOSEISMIC             1119
#define IDC_CHECK_NOLABELS2             1119
#define IDC_CHECK_VECTORIZE             1119
#define IDC_CHECK_NOLABELS_INSIDE       1119
#define IDC_CHECK_NOLABELS_INSIDE2      1121
#define IDC_CONVERSION_DZ               1122
#define IDC_CHECK_IS_NOLINES            1122
#define IDC_CHECK_IS_NOLINES2           1123
#define IDC_CHECK_IS_NONODES            1123
#define IDC_CHECK_IS_SEISCLIPBOARD      1124
#define IDC_CHECK_IS_SEISPLOT           1124
#define IDC_MIG_DXT                     1128
#define IDC_CHECK_MIGEK                 1130
#define IDC_CHECK_USEEXIST              1131
#define IDC_MIG_FXO                     1132
#define IDC_MIG_DXO                     1133
#define IDC_MIG_XMAX                    1134
#define IDC_MIG_DXM                     1135
#define IDC_MIG_DZT                     1136
#define IDC_RADIO_OPTIONS               1140
#define IDC_RADIO_OFFSETMIX             1141
#define IDC_CHECK_OFFSET                1142
#define IDC_CHECK_DISTANCE              1143
#define IDC_MIG_DXV                     1144
#define IDC_RADIO_OFFSET                1144
#define IDC_MIG_DZV                     1145
#define IDC_RADIO_REVERSE               1146
#define IDC_RADIO5                      1147
#define IDC_RADIO6                      1148
#define IDC_RADIO7                      1149
#define IDC_RADIO22                     1150
#define IDC_RADIO_SPHERICSRC            1151
#define IDC_RADIO23                     1151
#define IDC_RADIO24                     1152
#define IDC_MIG_TMAXRAY                 1153
#define IDC_VIEW__DIST1                 1155
#define IDC_VIEW__DIST2                 1156
#define IDC_VIEW__DIST3                 1157
#define IDC_RADIO_RECPLUS               1159
#define IDC_BUTTON_DXO                  1161
#define IDC_BUTTON_DISTSG               1167
#define IDC_ABOUT_PIC                   1170
#define IDC_BTN_HOMEPAGE                1173
#define IDC_BUTTON_AUTO                 1180
#define IDC_ZSHOT                       1181
#define IDC_BUTTON_EDIT                 1181
#define IDC_BUTTON_UNDO                 1181
#define IDC_EDIT_NEWNAME                1182
#define IDC_EDIT_X1                     1184
#define IDC_EDIT_Y1                     1185
#define IDC_EDIT_X2                     1186
#define IDC_EDIT_Y2                     1187
#define IDC_EDIT_LAYERNO                1189
#define IDC_BUTTON1                     1190
#define IDC_CHECK1                      1191
#define IDC_BUTTON2                     1191
#define IDC_EDIT_LAT1                   1192
#define IDC_BUTTON8                     1192
#define IDC_CHECK_ISSORT                1192
#define IDC_CHECK_IS_GS                 1192
#define IDC_EDIT1                       1193
#define IDC_BUTTON_EBCDIC               1193
#define IDC_BUTTON12                    1193
#define IDC_CHECK_ISSORTY               1193
#define IDC_EDIT_D1                     1194
#define IDC_EDIT2                       1194
#define IDC_CHECK_OUTPUT_NOLATLONG      1194
#define IDC_BUTTON9                     1194
#define IDC_BUTTON13                    1194
#define IDC_EDIT_LONG1                  1195
#define IDC_BUTTON3                     1195
#define IDC_EDIT_V2                     1195
#define IDC_EDIT_OBSDIST                1195
#define IDC_EDIT3                       1195
#define IDC_CHECK_INLINE                1195
#define IDC_EDIT_LAT2                   1196
#define IDC_SPIN_POS                    1196
#define IDC_BUTTON4                     1196
#define IDC_EDIT_D2                     1196
#define IDC_BUTTON_TEST                 1196
#define IDC_EDIT4                       1196
#define IDC_BUTTON14                    1196
#define IDC_EDIT_LONG2                  1197
#define IDC_BUTTON5                     1197
#define IDC_EDIT_V3                     1197
#define IDC_BUTTON_TEST2                1197
#define IDC_BUTTON15                    1197
#define IDC_EDIT_OBSDIST2               1197
#define IDC_SPIN                        1198
#define IDC_BUTTON6                     1198
#define IDC_EDIT_D3                     1198
#define IDC_BUTTON_TEST3                1198
#define IDC_BUTTON_TEST_TRCCOMB         1198
#define IDC_BUTTON16                    1198
#define IDC_BUTTON7                     1199
#define IDC_EDIT_V4                     1199
#define IDC_BUTTON10                    1199
#define IDC_BUTTON17                    1199
#define IDC_EDIT_D4                     1200
#define IDC_BUTTON11                    1200
#define IDC_BUTTON18                    1200
#define IDC_EDIT_V5                     1201
#define IDC_BUTTON_STACK                1201
#define IDC_BUTTON21                    1201
#define IDC_EDIT_D5                     1202
#define IDC_BUTTON_STACK2               1202
#define IDC_BUTTON_SEGYGEN              1202
#define IDC_BUTTON22                    1202
#define IDC_BUTTON19                    1203
#define IDC_BUTTON23                    1203
#define IDC_EDIT_D10                    1203
#define IDC_BUTTON20                    1204
#define IDC_EDIT_DEPTHMAX               1204
#define IDC_VIEW_UPDATE_TRACEACTIVE     1205
#define IDC_EDIT_GRAVDC                 1205
#define IDC_BUTTON_POS                  1206
#define IDC_BUTTON_NEG                  1207
#define IDC_BUTTON_MINC                 1208
#define IDC_BUTTON_MIDC                 1209
#define IDC_EDIT_TMIN                   1209
#define IDC_EDIT_V6                     1209
#define IDC_BUTTON_MIDC2                1210
#define IDC_EDIT_TMAX                   1210
#define IDC_EDIT_D6                     1210
#define IDC_BUTTON_MIDC3                1211
#define IDC_DLG_TABNAME                 1211
#define IDC_EDIT_V7                     1211
#define IDC_EDIT_NUMDIV                 1211
#define IDC_EDIT_FREQMAX                1211
#define IDC_BUTTON_MIDC4                1212
#define IDC_DLG_OUTNAME                 1212
#define IDC_EDIT_D7                     1212
#define IDC_BUTTON_MIDC5                1213
#define IDC_BUTTON_BROWSEO              1213
#define IDC_EDIT_V8                     1213
#define IDC_EDIT_D8                     1214
#define IDC_BUTTON_MIDC9                1214
#define IDC_EDIT_V1                     1215
#define IDC_BUTTON_MIDC6                1215
#define IDC_EDIT_V9                     1216
#define IDC_MIGSECNAME                  1216
#define IDC_BUTTON_MIDC7                1216
#define IDC_EDIT_D9                     1217
#define ID_DIGITIZE_MIGDXV              1217
#define IDC_BUTTON_MIDC8                1217
#define IDC_PROC_STOP                   1218
#define IDC_DIG_LABEL                   1220
#define IDC_CHECK_BITMAP                1221
#define IDC_EDIT_X                      1222
#define IDC_EDIT_Y                      1223
#define IDC_BMPSECNAME                  1224
#define IDC_EDIT_Y3                     1224
#define IDC_CHK_RENUMBER                1225
#define IDC_CHK_GSCA                    1226
#define IDC_BUTTON1_OFFSET              1227
#define IDC_CHK_USE_REDUCEDTIME         1227
#define IDC_FLOATNAME                   1228
#define IDC_CHK_CONV_ISDEADTRC_EXIST    1228
#define IDC_BUTTON1_OFFSET2             1228
#define IDC_PROC_TRACE1                 1229
#define IDC_STATIC1                     1229
#define IDC_MARKERLOCNAME               1229
#define IDC_CHK_USE_CDPDISTANCE         1229
#define IDC_TXNAME                      1229
#define IDC_CHK_CONV_EBC2ASC            1229
#define IDC_PROC_TRACE2                 1230
#define IDC_STATIC2                     1230
#define IDC_VRMSTAUNAME                 1230
#define IDC_TXNAME2                     1230
#define IDC_KM_SHIFT                    1230
#define IDC_CHK_CONV_ISOFFSETMM         1230
#define IDC_PROC_TRACESTEP              1231
#define IDC_STATIC3                     1231
#define IDC_CHK_CONV_IEEE               1231
#define IDC_CHK_IEEE_IBM                1231
#define IDC_PROC_SHOW                   1232
#define IDC_BUTTON_BROWSER1             1232
#define IDC_CHK_GSCA2                   1232
#define IDC_CHK_RESET_ZERO              1232
#define IDC_BUTTON_BROWSER2             1235
#define IDC_STATIC4                     1239
#define IDC_STATIC5                     1243
#define IDC_STATIC6                     1245
#define IDC_STATIC7                     1247
#define IDC_STATIC9                     1248
#define IDC_STATIC10                    1249
#define IDC_STATIC8                     1250
#define IDC_PROC_SHOW_WIENER            1251
#define IDC_STATIC11                    1251
#define IDC_FILE_MAXLAG                 1252
#define IDC_SET                         1253
#define IDC_STATIC12                    1253
#define IDC_EDIT_SHOWWIENER             1254
#define IDC_STATIC13                    1254
#define IDC_EDIT_EXPAND_RATIO           1255
#define IDC_EDIT_DIG_SELECTSEGMENT      1256
#define IDC_EDIT_DIG_TOTALSEGMENTS      1257
#define IDC_REDUCEVELOCITY_OLD          1257
#define IDC_REDUCEVELOCITY_NEW          1258
#define IDC_REDUCEVELOCITY_SOURCEKM     1259
#define IDC_RADIO_CALC                  1259
#define IDC_MODEL_ZINC                  1260
#define IDC_MODEL_XMIN                  1261
#define IDC_RADIO_OPTIONS3              1261
#define IDC_MODEL_XMAX                  1262
#define IDC_RADIO_OPTIONS4              1262
#define IDC_RADIO_OPTIONS5              1263
#define IDC_RADIO_SXSY_OVERWRITE        1265
#define IDC_CHECK_ISNEGTIVE_FROMLAT     1266
#define IDC_RICHEDIT_LATLONG            1267
#define IDC_RADIO_SXSY_OVERWRITE2       1267
#define IDC_EDIT_LATLONG_MULTI          1268
#define IDC_EDIT_TRACE1                 1269
#define IDC_EDIT_TRACE2                 1270
#define IDC_EDIT_LABEL_NUMWIDTH         1270
#define IDC_EDIT_LABEL_NUMHEIGTH        1271
#define IDC_EDIT_DAC                    1271
#define IDC_EDIT_LABEL_SIZE             1272
#define IDC_BUTTON_ZEROTRC              1272
#define IDC_LATLONGNAME                 1273
#define IDC_RADIO9                      1274
#define IDC_RADIO10                     1275
#define IDC_RADIO11                     1276
#define IDC_EDIT_ORG                    1276
#define IDC_RADIO12                     1277
#define IDC_RADIO13                     1278
#define IDC_ASSIGN_METHOD               1279
#define IDC_BUTTON_COLOR                1280
#define IDC_ASSIGN_METHOD2              1280
#define IDC_ISCOH                       1281
#define IDC_BUTTON_COLOR2               1281
#define IDC_EDIT_NUMDISPLAY             1282
#define IDC_EDIT_VELDISPLAY             1282
#define IDC_RADIO_MODE                  1283
#define IDC_RADIO_SUMMETHOD             1284
#define IDC_ISCOH2                      1285
#define IDC_ISTWTT                      1285
#define IDC_ISRAYTRACE                  1286
#define IDC_STATIC_VEL                  1287
#define IDC_PROC_TWINDOWSEC             1288
#define IDC_EDIT_LABEL                  1289
#define IDC_RADIO_4DECIMAL              1290
#define IDC_EDIT_YLABEL                 1290
#define IDC_PALETTENAME                 1291
#define IDC_AMPLEVEL1                   1292
#define IDC_BUTTON_COL1                 1293
#define IDC_BUTTON_COL2                 1294
#define IDC_AMPLEVEL2                   1295
#define IDC_EDIT_WAVELENGTH             1295
#define IDC_BUTTON_COL3                 1296
#define IDC_EDIT_MODULATION_DEPTH       1296
#define IDC_AMPLEVEL3                   1297
#define IDC_TRACE_AUTO                  1297
#define IDC_BUTTON_COL4                 1298
#define IDC_TRACE_AUTO2                 1298
#define IDC_EDIT_VALUE                  1298
#define IDC_AMPLEVEL4                   1299
#define IDC_EDIT_TLENGTH                1299
#define IDC_BUTTON_COL5                 1300
#define IDC_EDIT_TLENGTH2               1300
#define IDC_EDIT_GW                     1300
#define IDC_AMPLEVEL5                   1301
#define IDC_IS_BACKDELETE               1301
#define IDC_IS_SPIKE_ZEROING            1301
#define IDC_BUTTON_COL6                 1302
#define IDC_EDIT_SKIP                   1302
#define IDC_IS_SPIKE_ZEROING2           1302
#define IDC_AMPLEVEL6                   1303
#define IDC_EDIT_DECIMATE               1303
#define IDC_EDIT_TLAG                   1303
#define IDC_BUTTON_COL7                 1304
#define IDC_CHECK_APPLY4ALL             1304
#define IDC_AMPLEVEL7                   1305
#define IDC_INFILE                      1305
#define IDC_BUTTON_COL8                 1306
#define IDC_CHK_AMPSCALE                1306
#define IDC_AMPLEVEL8                   1307
#define IDC_SHIFT                       1307
#define IDC_MULT_FACTOR                 1307
#define IDC_BUTTON_COL9                 1308
#define IDC_VIEW_TMIN                   1308
#define IDC_AMPLEVEL9                   1309
#define IDC_VIEW_TMAX                   1309
#define IDC_BUTTON_COL10                1310
#define IDC_VIEW_TMAX2                  1310
#define IDC_VIEW_DT                     1310
#define IDC_VIEW_DTRATIO                1310
#define IDC_AMPLEVEL10                  1311
#define IDC_CHK_NMOPANELS               1311
#define IDC_BUTTON_COL0                 1312
#define IDC_PROC_WINDOW_SLIDING         1312
#define IDC_CHK_NMOPANELS2              1312
#define IDC_CHK_LAT_BASED               1312
#define IDC_CHK_NORM                    1312
#define IDC_AMPLEVEL0                   1313
#define IDC_CHK_FACTORMIL               1313
#define IDC_AMPCLIP                     1314
#define IDC_RADIO_SORT                  1314
#define IDC_BUTTON_COL11                1314
#define IDC_BUTTON_CURVE                1314
#define IDC_CHECK_GUNDELAY              1315
#define IDC_EDIT_FIRERATE1              1316
#define IDC_CHECK_ALL                   1316
#define IDC_CHECK_PARTIAL               1316
#define IDC_EDIT_FIRERATE2              1317
#define IDC_IS_ENERGY                   1317
#define IDC_CHECK_INTZERO               1317
#define IDC_EDIT_FIRERATE3              1318
#define IDC_EDIT_TRACESPLIT             1318
#define IDC_TLAG                        1318
#define IDC_CHECK_INTZERO2              1318
#define IDC_CHECK_ISMONO                1318
#define IDC_TMIN                        1319
#define IDC_BUTTON_COLORBAR             1319
#define IDC_TMAX                        1320
#define IDC_TLAG_WEIGHT                 1320
#define IDC_LAG_WEIGHT                  1320
#define IDC_STATIC_DRAGDROP             1320
#define IDC_STATIC_DRAGDROP2            1321
#define IDC_MULTIPLY                    1321
#define IDC_IS_MINUS_OFFSET             1321
#define IDC_PROC_METHOD                 1322
#define IDC_FACTOR                      1322
#define IDC_STATIC_DRAGDROP3            1322
#define IDC_STATIC_CURVE                1322
#define IDC_PROC_METHOD2                1323
#define IDC_BUTTON_NEWCOLOR             1323
#define IDC_PROC_METHOD3                1324
#define IDC_BUTTON_NEWBW                1324
#define IDC_PROC_METHOD4                1325
#define IDC_EDIT_MODELEX                1325
#define IDC_PROC_TRCMIX                 1326
#define IDC_DISTANCE0                   1327
#define IDC_EDIT_VELMODEX               1328
#define IDC_BASEVEL                     1329
#define IDC_TRACES_INS                  1330
#define IDC_BASEVEL2                    1330
#define IDC_BASEDEPTH                   1330
#define IDC_STATIC_OPTIONAL             1332
#define IDC_MODEL_THEORY_A              1333
#define IDC_MODEL_THEORY_B              1334
#define IDC_MODEL_THEORY_ALPHA          1335
#define IDC_MODEL_THEORY_BETA           1336
#define IDC_RADIO_DOMAIN                1337
#define IDC_RADIO_DOMAIN2               1338
#define IDC_AUTO                        1338
#define IDC_EDIT_HARDID_MULTI           1339
#define IDC_EDIT_EMAIL                  1340
#define IDC_VALUE                       1340
#define IDC_LAYER1                      1341
#define IDC_LAYER2                      1342
#define IDC_CHECK_REGRESSION            1345
#define IDC_STR_REGRESSION              1346
#define IDC_BUTTON_MAPPING              1347
#define IDC_STR_REGRESSION2             1347
#define IDC_STR_REGRESSION_X            1347
#define IDC_EDIT_COMMENTS               1348
#define IDC_EDIT_NAME                   1349
#define IDC_EDIT_PHONE                  1350
#define IDC_EDIT_TEXT_MULTILINE         1351
#define IDC_BUTTON_TRACE                1352
#define IDC_IS_BYMIL                    1353
#define IDC_IS_FORWARD                  1354
#define IDC_IS_INBETWEEN                1355
#define IDC_EDIT_P1                     1356
#define IDC_EDIT_P2                     1357
#define IDC_EDIT_PMIN                   1358
#define IDC_EDIT_PMAX                   1359
#define IDC_EDIT_NP                     1360
#define IDC_EDIT_P3                     1361
#define IDC_EDIT_DP                     1362
#define IDC_EDIT_DXAVG                  1363
#define IDC_EDIT_P4                     1364
#define IDC_OUTFILE2                    1365
#define IDC_EDIT_NOISE_THRESHALD        1366
#define IDC_EDIT_XWIN                   1367
#define IDC_EDIT_TWIN                   1368
#define IDC_EDIT_XWIN_NUMMAX            1369
#define IDC_IS_ALLTRACES                1370
#define IDC_EDIT_SUSCEPT                1371
#define IDC_EDIT_ANGINC                 1372
#define IDC_EDIT_ANGSTR                 1373
#define IDC_ANGSTR                      1374
#define IDC_EDIT_OFFSET                 1376
#define IDC_BUTTON_CALC                 1377
#define IDC_CHECK_NO_NODE_NAV           1378
#define IDC_CHECK_NO_NODE_NAV2          1379
#define IDC_CHECK_IS_VIEWXML            1379
#define IDC_CHECK_PROMPT                1379
#define IDC_CHECK_NO_NODE_NAV3          1380
#define IDC_CHECK_NOSHOW_AGAIN          1380
#define IDC_CHECK_MARKUP_ERROR          1381
#define IDC_BUTTON_CALC2                1381
#define IDC_EDIT_NUMCOLORS              1382
#define IDC_EDIT_VALUE1                 1383
#define IDC_EDIT_VALUE2                 1384
#define IDC_DT                          1384
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_VIEW_TIMESECTION             32773
#define ID_VIEW_DEPTHSECTION            32774
#define ID_VIEW_VELOCITYCOLORMAP        32775
#define ID_VIEW_ADDRANGETOSEGY          32776
#define ID_VIEW_BOTH                    32777
#define ID_EDIT_TRAVELTIME              32778
#define ID_VIEW_CONTOURS                32779
#define ID_VIEW_RAYTRACE                32780
#define ID_EDIT_DIGITIZE                32781
#define ID_EDIT                         32782
#define ID_EDIT_SAVEDIG                 32783
#define ID_EDIT_NEWCURVE                32785
#define ID_DIGITIZE_FINISHDIGITIZING    32786
#define ID_PROCESSING_TRACEREORDER      32787
#define ID_PROCESSING_COHMIX            32788
#define ID_TOOLBAR_NEWMOD               32789
#define ID_EDIT_BOUNDARY                32790
#define ID_PROCESSING_RAYTRACING        32791
#define ID_EDIT_VELOCITY                32792
#define ID_PROCESSING_REVERSERANGE2     32793
#define ID_EDIT_NONODES                 32794
#define ID_PROCESSING_REVERSERANGE      32795
#define ID_PROCESSING_LOADZELTSMODEL    32796
#define ID_PROCESSING_DATAREDUCTIONANDFILTER 32797
#define ID_PROCESSING_LATERALSHIFT      32798
#define ID_PROCESSING_RAYTRACE          32799
#define ID_PROCESSING_RAYPATH           32800
#define ID_VIEW_SEGYINFO                32801
#define ID_PROCESSING_DEFINESOURCEPOSITION 32802
#define ID_TOOLBAR_PICK                 32803
#define ID_TOOLBAR__REMOVE              32804
#define ID_TOOBAR_MOVE                  32805
#define ID_TOOLBAR_ADD                  32806
#define ID_TOOLBAR_NEWLINE              32807
#define ID_TOOLBAR_DELLINE              32808
#define ID_TOOLBAR_SAVEV                32809
#define ID_TOOLBAR_SAVEASV              32810
#define ID_EDIT_NOLABLES                32811
#define ID_EDIT_DISPLAYTUNEUP_ADDREMOVENODESANDBOUNDARIESINDISPLAY 32812
#define ID_EDIT_TUNEUP_NOBOUNDARY       32813
#define ID_EDIT_TUNEUP_NOCOLORMAP       32814
#define ID_EDIT_DISPLAYTUNEUP_ADDREMOVEOBSPOSITIONS 32815
#define ID_EDIT_TUNEUP_OBSPOSITIONS     32816
#define ID_TOOLBAR_DUPLICATE            32818
#define ID_PROCESSING_CHECKMODELINTEGRITY 32819
#define ID_TOOLBAR_RESIZEMOD            32820
#define ID_EDIT_DISPLAYTUNEUP_FILLAREASMALL 32821
#define ID_EDIT_DISPLAYTUNEUP_FILLAREAONCE 32822
#define ID_DIGITIZE_UNDOPOINT           32823
#define ID_PROCESSING_APPENDASEGYFILE   32824
#define ID_PROCESSING                   32825
#define ID_PROCESSING_REDUCEMANUAL      32826
#define ID_VIEW_SEGYPREVIEW             32827
#define ID_MODELING_MERGEMODELS         32828
#define ID_PROCESSING_MIGRATION         32829
#define ID_MODELING_EXTRACTVELOCITYDEPTHCURVE 32830
#define ID_MODELING_EXTRACTVZCURVE      32831
#define ID_TOOLBAR_SEPA                 32833
#define ID_MENUITEM32834                32834
#define ID_MENUITEM_PC2UNIX             32835
#define ID_PROCESSING_PC2UNIX           32836
#define ID_PROCESSING_UNIX2PC           32837
#define ID_PROCESSING_KDMIG             32839
#define ID_PROCESSING_KDMIGPOST         32840
#define ID_MENUITEM32841                32841
#define ID_MENU_TIMESECTRC              32842
#define ID_VIEW_TIMESECTRC              32843
#define ID_PROCESSING_KDMIGSIMPLE       32844
#define ID_MENUITEM32845                32845
#define ID_MENU_VIEW_HYDRO              32846
#define ID_MENUITEM32847                32847
#define ID_PROCESSING_SB                32848
#define ID_MENUITEM32849                32849
#define ID_PROCESSING_SB_KM             32850
#define ID_PROCESSING_CONV              32852
#define ID_MODELING_EXTRACTLAYERINFORMATION 32854
#define ID_MODELING_EXTRACTLAYERINFOR   32855
#define ID_TOOLBAR_REFRESH              32856
#define ID_MODELING_LOADREIDSMODEL      32860
#define ID_PROCESSING_CALCULATORLATLONGTODISTANCE 32861
#define ID_PROCESSING_LATLONGTODISTANCE 32862
#define ID_EDIT_DISPLAYTUNEUP_BIGMODELNODES 32863
#define ID_EDIT_DISPLAYTUNEUP_CHANGINGCOLOROFTRAVELTIMECURVES 32864
#define ID_EDIT_DISPLAYTUNEUP_CHANGCOLORTTCURVES 32865
#define ID_PROCESSING_UNIX2PCBATCH      32866
#define ID_PROCESSING_PC2UNIXBATCH      32867
#define ID_PROCESSING_RAWTOSEGY         32868
#define ID_VIEW_TRACEANALYSIS           32869
#define ID_PROCESSING_CONVERTDOBSDATATOSEGYUSINGSHOTTABLE 32870
#define ID_PROCESSING_CONVERTDATATOSEGY 32871
#define ID_PROCESSING_GENERATESHOTTABLEFROMNAVIGATIONLOGS 32872
#define ID_PROCESSING_NAVLOGTOTAB       32873
#define ID_DIGITIZING_LOADEXISTINGDIGITIZINGFILE 32874
#define ID_DIGITIZING_LOADEXISTING      32875
#define ID_EDIT_DISPLAYTUNEUP_OVERLAYEXTERNALLINEDRAWINGS 32876
#define ID_EDIT_DISPLAYTUNEUP_EXTERNAL_DRAWINGS 32877
#define ID_EDIT_DISPLAYTUNEUP_EXTERNAL_DRAWINGS_TIM 32878
#define ID_PROCESSING_DUMPCDPDISTANCE   32879
#define ID_MODELING_CONVERTMODELTOVELOCITYASDENSITYBLOCKS 32880
#define ID_MODELING_DENBLOCKS           32881
#define ID_DIGITIZING_MIGRATELINEDRAWINGS 32882
#define ID_DIGITIZING_CHANGECURVERESOLUTION 32883
#define ID_DIGITIZING_CHANGECURVERES    32884
#define ID_DIGITIZING_LOADZELT_TX       32885
#define ID_DIGITIZING_WHEREANI          32887
#define ID_EDIT_DISPLAYTUNEUP_SKIPCOMPLAININGTRACETOODENSE 32888
#define ID_EDIT_DISPLAYTUNEUP_SKIPTOODENSE 32889
#define ID_DIGITIZING_SHIFTDIGITING     32893
#define ID_DIGITIZING_CHANGEERRORBAR_ASBAR 32894
#define ID_DIGITIZING_CHANGEERRORBAR_ASCIRCLE 32895
#define ID_DIGITIZING_CHANGEERRORBAR_ASSTAR 32896
#define ID_DIGITIZING_CHANGEERRORBAR_ASFILLCIRCLE 32897
#define ID_EDIT_DISPLAYTUNEUP_REMOVEOUTSIDERAYPOINTS 32898
#define ID_TOOLBAR_FLIPMOD              32899
#define ID_MODELING_SUBSIDENCEBEFORESEDIMENTLOADING 32900
#define ID_FILE_EXPORTBITMAP            32901
#define ID_FILE_IMPORTBITMAP            32902
#define ID_FILE_IMPORTBITMAP_RESIZEBITMAP 32904
#define ID_FILE_RESIZEBITMAP            32905
#define ID_PROCESSING_TDCONVBMP         32906
#define ID_EDIT_DISPLAYTUNEUP_LABELASTWTT 32907
#define ID_PROCESSING_DATARESAMPLE      32908
#define ID_TOOLBAR_REFRESH_ALL          32910
#define ID_EDIT_DISPLAYTUNEUP_MODELPROPERTIES_REMOVEOVERLAYOFTTCURVES 32911
#define ID_EDIT_DISPLAYTUNEUP_REMOVETTOVERLAY 32912
#define ID_TOOLBAR_ZOOM                 32913
#define ID_TOOLBAR_UNZOOM               32914
#define ID_PROCESSING_DEBIAS            32915
#define ID_PROCESSING_WIENER            32916
#define ID_DIGITIZING_EXPAND_SEGMENTS   32917
#define ID_DIGITIZING_RESIZE_SEGMENTS   32918
#define ID_MODEL_SHIFTXZ                32919
#define ID_DIGITIZING_SELECT_CURRENT    32920
#define ID_DIGITIZING_ZELTSFORMAT_REDEFINESOURCEPOSITION 32921
#define ID_DIGITIZING_CHANGEERRORBAR_REDEFINESOURCE 32922
#define ID_DIGITIZING_ZELTSFORMAT_TOGGLEZPLOTSUPPORT 32923
#define ID_DIGITIZING_ZELTSFORMAT_TOGGLEZPLOT 32924
#define ID_PROCESSING_CHANGEREDUCEVELOCITYFORBMP 32925
#define ID_MODELING_MOVEBOUNDARY        32926
#define ID_PROCESSING_CHOPDATA          32927
#define ID_VIEW_STACKINGVELOCITYMAP     32928
#define ID_TOOLBAR_BIGGER               32929
#define ID_TOOLBAR_LESS                 32930
#define ID_PROCESSING_APPENDMANYSEGYFILES 32931
#define ID_EDIT_DISPLAYTUNEUP_ADJUSTINGLABELSIZES 32932
#define ID_DIGITIZING_SPLIT             32933
#define ID_DIGITIZING_REVISELINELABEL   32934
#define ID_EDIT_DISPLAYTUNEUP_MODELPROPERTIES_LINEDRAWINGLABEL 32935
#define ID_DIGITIZING_RAYCODES          32936
#define ID_TOOLBAR_HAND                 32938
#define ID_DIGITIZING_SAVEDIGITIZEWITHFFID 32939
#define ID_DIGITIZING_SAVEDIGFFID       32940
#define ID_TIME_FORWIDE                 32941
#define ID_VIEW_VELOCITYCOLORMAPINTWTT  32942
#define ID_VIEW_VELOCITYCOLORTWTT       32943
#define ID_TIME_FORWIDE_SEMB            32944
#define ID_TIME_FORWIDE32945            32945
#define ID_TIME_FORWIDE_NMOVELOCITY     32946
#define ID_VIEW_NMO                     32947
#define ID_VIEW_NMO_VELOCITY            32948
#define ID_MODELING_MERGEMODEL          32949
#define ID_MODELING_GENERATESYNTHETICSEGYDATA 32950
#define ID_PROCESSING_TIME              32951
#define ID_MODELING_DOSCONSOL           32952
#define ID_TIME_TIMESECTIONWITHPERTURBEDTRAVEL 32953
#define ID_DISPLAYTUNE_OVERWRITEXLABEL  32954
#define ID_PROCESSING_TIME32955         32955
#define ID_PROCESSING_TIME32956         32956
#define ID_PROCESSING_TIME32957         32957
#define ID_PROCESSING_TIME32958         32958
#define ID_PROCESSING_TIMEDEPTH_CONV    32959
#define ID_MODELING_DISPLAYTRAVEL       32960
#define ID_MODELING_DISPLAYCIRCLE       32961
#define ID_MODELING_ADDSINESHAPETOBOUNDARY 32966
#define ID_MODELING_ADDSINESHAPE        32967
#define ID_PROCESSING_DATADESPIKE       32968
#define ID_ACCELERATOR_FONTSIZE         32969
#define ID_ACCELERATOR_FONTMINUS        32970
#define ID_DISPLAYTUNE_LABELSIZEINCREASE 32972
#define ID_DISPLAYTUNE_LABELSIZEDECREASE 32973
#define ID_MODELING_DUMPMODELINCMP      32977
#define ID_MODELING_DUMPCMP_TWTT        32978
#define ID_PROCESSING_DUMPLAT           32979
#define ID_PROCESSING_DUMPSEGYLATLONG   32980
#define ID_PROCESSING_DECIMATEDATALINES 32981
#define ID_ZELT_SWAPPOINTSAROUNDSOURCE  32982
#define ID_ZELT_SWAPAROUNDSOURCE        32983
#define ID_DIGITIZING_ZELT_SWAPSOURCE   32984
#define ID_PROCESSING_TIMEDEPTH_DRAWINGS 32985
#define ID_SEGYCONVERSION_UNIXTOPCCONVERT 32986
#define ID_MODELUP                      32987
#define ID_MODELDOWN                    32988
#define ID_MODELING_MOVEBOUNDARYDOWNORVELDOWN 32989
#define ID_EDIT_REDO32991               32991
#define ID_BUTTON32994                  32994
#define ID_MODELING_TOGGLEPEGLETMULTIPLEINDEPTH 32995
#define ID_MODELING_TOGGLEPEGLET        32996
#define ID_EDIT_TEXT                    32997
#define ID_ACCELERATOR32999             32999
#define ID_MODELING_TOGGLESWAVELABELING 33002
#define ID_MODELING_TOGGLESWAVELABELS   33003
#define ID_PROCESSING_DATASPLIT         33004
#define ID_PROCESSING_SONOBUOY          33005
#define ID_PROCESSING_ID_PROCESSING_TRACEDUB 33006
#define ID_PROCESSING_TOOLS             33007
#define ID_TOOLS_GET                    33008
#define ID_TOOLS_MAPCONVERTTIME         33009
#define ID_PROCESSING_SPHERICALCORRECTIONATTENUATION 33010
#define ID_PROCESSING_SPHERICALCORRECTION 33011
#define ID_PROCESSING_ADDDATA           33013
#define ID_TIME_RMSVELOCITYANALYSIS     33014
#define ID_Menu                         33015
#define ID_Menu_TRACEBALANCING          33016
#define ID_MODELING_CONVERSION          33018
#define ID_MODELCONVERSION_MODELTORMSVELOCITY 33019
#define ID_MODELCONVERSION_TORMSVELOCITY 33020
#define ID_MODELCONVERSION_RMSVELOCITYTO 33021
#define ID_MODELCONVERSION_RMS_INT_TWTT 33022
#define ID_MODELCONVERSION_RMS_INT_DEPTH 33024
#define ID_MODELCONVERSION_RMS_INT_MODELKM 33026
#define ID_MODELCONVERSION_RMS_INT_TWTT2 33027
#define ID_MODELCONVERSION_TORMSVELOCITY2 33028
#define ID_PROCESSING_SONOBUOY33029     33029
#define ID_SONOBUOY_AUTOCALCULATEOFFSETFROMLAT 33030
#define ID_SONOBUOY_ASSOCIATEKMUSINGPOLYNOMIAL 33031
#define ID_SONOBUOY_POLY                33032
#define ID_DISPLAYTUNE_TOGGLEIBMFLOATINGMODE 33033
#define ID_OPTIONS_TOGGLEIBMFLOATINGMODE 33034
#define ID_SEGYCONVERSION_IEEETOIBMFLOAT 33035
#define ID_SONOBUOY_AUTO                33036
#define ID_SONOBUOY_AUTODIG             33037
#define ID_PROCESSING_DATANORMALIZE     33038
#define ID_PROCESSING_TRACEFILTER       33039
#define ID_PROCESSING_FILTER_OFFSETVARYING 33040
#define ID_SONOBUOY_ASSIGNOFFSETFROMANOTHERSEGY 33041
#define ID_SONOBUOY_ASSIGNOFFSETFROMSEGY 33042
#define ID_FILE_SAVEASDEFAULTS          33043
#define ID_PROCESSING_GAINADJUSTMENT    33044
#define ID_PROCESSING_GAINADJUST        33045
#define ID_PROCESSING_TRACESUBTRACTALONGCURVE 33053
#define ID_PROCESSING_SPLITODDEVENTRACES 33054
#define ID_REFLECTION_FAULTDETECTION    33055
#define ID_REFLECTION_FAULTENHANCING    33056
#define ID_REFLECTION_COHERENCY         33057
#define ID_REFLECTION_COHERENCYPLOT     33058
#define ID_TOOLS_DUMPPOLYNOMIALSTODISCRETEPOINTS 33059
#define ID_TOOL_DUMPPOLYNOMIALSPOINTS   33060
#define ID_TOOL_DUMPPOLYNOMIALPOINTS    33061
#define ID_WIDE_NMOSTRETCHING           33062
#define ID_Menu_TRACEBALANCEXT          33063
#define ID_Menu_TRACEBALANCE_XT         33064
#define ID_SONOBUOY_SHIFTTRACENUMBER    33065
#define ID_MODELTOOLS_PICKNEXTBOUNDARY  33066
#define ID_TOOLS_PICKNEXT               33067
#define ID_PROCESSING_DISTANCEADJUSTMENT 33068
#define ID_REFLECTION_FLATTENBOUNDARY   33069
#define ID_MODELING_TOGGLETHEORETICALMODELCURVES 33070
#define ID_MODELING_THEORETICALCURVES   33071
#define ID_HELP_ID                      33072
#define ID_HELP_LICENSESTATUS           33073
#define ID_MODELTOOLS_PERTURBVELOCITY   33074
#define ID_MODEL_PERTURBVEL             33075
#define ID_MODELTOOLS_TOGGLERAYDETAILS  33076
#define ID_MODEL_TOGGLERAYDETAILS       33077
#define ID_VIEW_SIZINGOFGRAPH           33078
#define ID_EDIT_LABEL_INSIDE            33079
#define ID_EDIT_LABLES_OUTSIDE          33080
#define ID_OPTIONS_TOGGLEIMAGESTRETCHMODE 33081
#define ID_OPTIONS_IMAGESTRETCHMODE     33082
#define ID_EDIT_IMAGESTRETCHMODE        33083
#define ID_OPTIONS_TOGGLEHORIZONTALGRIDS 33084
#define ID_PROCESSING_MODIFYASCIIHEADER 33086
#define ID_PROCESS_ASCIIHEADER          33087
#define ID_PROCESSING_TAUPSLANTSTACK    33088
#define ID_PROCESSING_TAUPINV           33089
#define ID_PROCESSING_TIME33090         33090
#define ID_PROCESSING_TFDN              33091
#define ID_PROCESSING_FREQUENCYSPECTRUM 33092
#define ID_PROCESSING_SPECTRUM          33093
#define ID_MODELING_M                   33097
#define ID_MODELING_MAG                 33098
#define ID_IMPORT_RESIZEBITMAP          33099
#define ID_IMPORT_BITMAP2SEGY           33100
#define ID_IMPORT_RESIZEBITMAP33101     33101
#define ID_SONOBUOY_ASSIGNOFFSETFORANYCHOSENTRACE 33102
#define ID_OFFSET_CHOSENTRACE           33103
#define ID_MODELING_GRAVITYMODELINGWITHDENSITYPLOTS 33104
#define ID_MODELING_GRAVITYMODELING_DENPLOT 33105
#define ID_MODELING_ACTIVATEOVERLAIDMODELFOREDITING 33106
#define ID_MODELING_ACTIVATEOVERLAIDMODEL 33107
#define ID_SONOBUOY_VOPY                33108
#define ID_SONOBUOY_COPY                33109
#define ID_SONOBUOY_COPYDATA            33110
#define ID_SONOBUOY_OFFSETJITTERINGREMOVAL 33111
#define ID_VIEW_USAGELOG                33112
#define ID_MODELING_RAYTRACEWITHDEBUG   33113
#define ID_OPTIONS_TOGGLECLIPCHANGEWITHGAIN 33114
#define ID_TOOLS_DUMPLAT                33115
#define ID_MODELTOOLS_GENERATEKMLFROMMANYMODELS 33116
#define ID_MODELTOOLS_GENERATEKML       33117
#define ID_SEGYCONVERSION_FORCEUNIX     33118
#define ID_SONOBUOY_AUTOINTERPOLATEINVALIDOFFSETS 33119
#define ID_MODELING_RAYTRACE            33120
#define ID_RAYTRACE_DEBUG               33121
#define ID_MODELING_FLATTENHORIZON      33122
#define ID_MODEL_TOGGLEDETAILS          33123
#define ID_VIEW_FREECACHEMEMORY         33124
#define ID_WIDE_NORMALIZETRACEINTERVAL  33125
#define ID_WIDE_DEFINESRC               33126
#define ID_TOOLS_CALCULATOR             33127
#define ID_TOOLS_CALC_POISSON           33128
#define ID_MODELING_SETHORIZONLIMITSWITHRAYPATHS 33129
#define ID_WINDOW_TILEVERTICAL          33130
#define ID_OPTIONS_SHOWANIMATION        33131
#define ID_SHOW3D_ANIMATION             33132
#define ID_BUTTON33133                  33133
#define ID_BUTTON33134                  33134
#define ID_BUTTON33135                  33135
#define ID_BUTTON33136                  33136
#define ID_BUTTON33143                  33143
#define ID_BUTTON33144                  33144
#define ID_REFLECTION_ASSOCIATEKMTOTRACEFROMFILE 33145
#define ID_DIGITIZING_CURVESTOSEGYTRACES 33146
#define ID_DIGITIZING_ENDCURVESTOSEGY   33147
#define ID_DIGITIZE_CURVESTOSEGY        33148
#define ID_DIGITIZE_ENDCURVESTOSEGY     33149
#define ID_DIGITIZING_DEFINEX           33150
#define ID_DIGITIZE_DEFINE_XVAL         33151
#define ID_DIGITIZING_BITMAPTOSEGY      33152
#define ID_BITMAPTOSEGY_OK              33153
#define ID_MODELTOOLS_DUMPVELOCITYRANGETOKML 33154
#define ID_BITMAPS_TIMELINEREMOVAL      33155
#define ID_PROCESSING_RESETSAMPLERATE   33156
#define ID_DIGITIZING_SHOWFILE          33157
#define ID_VIEW_REDUCEDNMO              33162
#define ID_TOOLS_INTERPOLATEINVALIDTRACESTARTTIME 33163
#define ID_TOOLS_INTERP_INVALID_T0      33164
#define ID_DIGITIZING_SWITCHDIGITIZINGFILE 33165
#define ID_DIGITIZING_STARTDIGITIZINGMARKER 33169
#define ID_DIGITIZING_STARTMARKER       33170
#define ID_FILE_OPENPROJECT             33171
#define ID_FILE_CLOSEPROJECT            33172
#define ID_FILE_SAVEPROJECT             33173
#define ID_REFLECTION_Z                 33174
#define ID_REFLECTION_ZT                33175
#define ID_WIDE_COMPUTEOFFSETSFROMSRC   33176
#define ID_WIDE_OFFSETSFROMSRC          33177
#define ID_DIGITIZING_SAVEHALFUNCERTAINTY 33178
#define ID_VIEW_GRAVITYCONT             33179
#define ID_VIEW_GRAVITYMODELVIEW        33180
#define ID_VIEW_GRAVITYCONT2            33181
#define ID_INDICATOR_XY                 61446
#define ID_VIEW_CONV                    65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        302
#define _APS_NEXT_COMMAND_VALUE         33182
#define _APS_NEXT_CONTROL_VALUE         1385
#define _APS_NEXT_SYMED_VALUE           128
#endif
#endif
